### PR TITLE
Adds a podcast feed URL

### PR DESCRIPTION
**Pull request by aubm**
If I understood you well, this could be the basic idea :)

Linked to #3

### CODE REVIEW

**Comment by aubm** [comment]
If it looks OK to you, I can help collecting the URLs.

**Comment by johnreutersward** [comment]
Thank you, It looks promising! 👍 

I will take a closer look at the PR and change some things if you don't mind.

I'd be happy to have some help collecting the Media URL's. I will make sure they are added to the production DB once this has landed.

**Comment by aubm** [comment]
Hey! Of course please change it as you like, or do it another way, I will not mind :)

**Comment by johnreutersward** [comment]
Hi @aubm, I merged your changes into a feature branch for me to work on. It turns out that we also need runtime (in seconds) for each episode so I have added a new field for that.

**Comment by aubm** [comment]
Ok cool :) I prefer your implementation by the way, it is simpler.

**Comment by aubm** [comment]
Can't wait to add the podcast to iTunes :p

**Comment by johnreutersward** [comment]
Hey @aubm, would you mind testing to see if https://gopherpods.appspot.com/feed-audio works with iTunes. 

It seems to work with the podcast app I use on android.

**Comment by aubm** [comment]
Hey! It seems to work fine, thanks! :)

**Pull request merged**
